services:
  mongo:
    image: mongo:6
    container_name: amapet-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - amapet-network

  mongo-express:
    image: mongo-express:latest
    container_name: amapet-mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo        # <-- service name of Mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER}   # web login username
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}   # web login password
    networks:
      - amapet-network      # can talk to mongo
      - npm          # optional: make accessible through nginx-proxy-manager
    # Expose port only if you want direct access
    ports:
      - "8085:8081"

  backend:
    build:
      context: ../backend
    container_name: amapet-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    depends_on:
      - mongo
    networks:
      - amapet-network
      - npm

  frontend:
    build:
      context: ../frontend
    container_name: amapet-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - amapet-network
      - npm

networks:
  amapet-network:
  npm:
    external: true
    name: nginx-proxy-manager_default

volumes:
  mongo-data:
